### ISSUE TITLE
REST API unavailable when HA is activated

### ISSUE THREAD

**Issue by darylounet** [sophos-iaas/chef-sophos-sg#1] opened 2017-01-31 08:14 UTC
When High Availability is activated (only tested master-slave) on Sophos UTM 9.409-9, it is impossible to activate REST API.

**Comment by threez** [comment] 2017-01-31 08:29
Thanks for your feedback. The issue is resolved in UTM 9.410 which will be published soon.

**Closed as completed by threez** 2017-01-31 08:29 UTC
